version: '3.8'

services:
  notex-doc:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "3344:3344"
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:3344/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s 